title: "Project LIPAD (Leveraging Intelligent Processing for Aircraft Damage): A DLSU-DMEM × Cebu Pacific Research Partnership"
description: "This collaborative research aims to develop a drone-based inspection system using depth cameras, computer vision, and digital twin technology for automated aircraft damage detection and assessment."
theme: jekyll-theme-minimal
markdown: kramdown
