title: "Project LIPAD (Leveraging Intelligent Processing for Aircraft Damage)"
description: "The DLSU-DMEM × Cebu Pacific research partnership develops a drone-based inspection system using depth cameras, computer vision, and digital twin technology for automated aircraft damage detection and assessment."
theme: jekyll-theme-minimal
markdown: kramdown
