title: "DLSU-DMEM × Cebu Pacific Research Partnership"
description: "The research partnership develops a drone-based inspection system using depth cameras, computer vision, and digital twin technology for automated aircraft damage detection and assessment."
theme: jekyll-theme-minimal
markdown: kramdown
